version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password # Set the root password
      MYSQL_DATABASE: pet_care_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5

  pet-care-app:
    build: .
    container_name: pet-care-app
    ports:
      - "9192:9192"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/pet_care_db
      DB_USERNAME: root
      DB_PASSWORD: password
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: