version: '3.8'

services:
  universal-pet-care:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9192:9192"
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/pet_care_db
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      mysql:
         condition: service_healthy
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pet_care_db
    ports:
      - "3307:3306"  # Change the host port to 3307
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge